name: CI/CD to Render

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Run tests (skip if none)
        run: npm test || echo "No tests"

      - name: Build Docker image
        run: docker build -t todo-api:latest .

      - name: Push deploy hook to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK" ]; then
            curl -X POST $RENDER_DEPLOY_HOOK
            echo "Triggered Render deploy hook"
          else
            echo "No Render deploy hook found"
          fi
